### ISSUE TITLE
Shopping List for the Space Rover Mission Build 2

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/space-rover-mission#57]
**Space Rover List**
Rough Estimate of the costs. All prices are in CAD. 
The same amount of person/weeks will be needed for each Option. Option 2 might require additional wait time to obtain the parts due to shipping delays.
 
Option 1 - If re-purposing existing Space Rover Build 1:
- [x] - [RFID Sensor](https://www.amazon.ca/Gikfun-RFID-Kit-Raspberry-EK1112x2C/dp/B07FFN54LS/ref=sr_1_1_sspa?crid=31N4OQKTA11WX&keywords=rc522&qid=1650649543&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=rc522%2Caps%2C118&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyUkQyQ1hETjE2UTdJJmVuY3J5cHRlZElkPUEwNDk4NjMxMkFUS0dMM0hGNDBEWiZlbmNyeXB0ZWRBZElkPUEwNDA3ODU1MkYzOEdFUjFURzJJUSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=) - $12
- [x] - [RFID cards](https://www.amazon.ca/YARONGTECH-13-56MHZ-14443A-Printable-Classic-Plastic/dp/B075XH4JLP/ref=sr_1_27?crid=31N4OQKTA11WX&keywords=rc522&qid=1650649543&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=rc522%2Caps%2C118&sr=8-27&th=1) - $15
- [x] - [NFC tags](https://www.amazon.ca/SKAYIN-NTAG215-Sticker-Perfectly-NFC-Enabled/dp/B097D63X68/ref=sr_1_3_sspa?crid=3QTLV9JG5PI5F&keywords=ntag215%2Bblack%2Bbig%2Bstickers&qid=1650651247&sprefix=ntag215%2Bblack%2Bbig%2Bstickers%2Caps%2C98&sr=8-3-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExNzkwQjRESTUzVFBPJmVuY3J5cHRlZElkPUEwNjY5MjA3MlpPUTVGUEZaRUM0SSZlbmNyeXB0ZWRBZElkPUEwNzA0OTg4M1BDMU5HTDcxQjFYUSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1) - $15
- [x] - [RC Chassis Base](https://www.canadarobotix.com/products/1596) - $36
- [ ] - [7.2V NiMH Battery](https://www.amazon.ca/gp/product/B002PXISDG/ref=ox_sc_saved_title_1?smid=A2AOMP7GTQZFW0&psc=1) - $44
- [ ] - [NiMH Battery Charger](https://www.amazon.ca/gp/product/B003MXMJX8/ref=ox_sc_saved_title_2?smid=A2AOMP7GTQZFW0&psc=1) - $32
- [x] - [TB6612FNG H-Bridge Motor Driver](https://www.amazon.ca/Robojax-Toshiba-TB6612FNG-Driver-Dual-H-Bridge/dp/B07ZTY692T/ref=sr_1_2?crid=E08575SO8LYL&keywords=TB6612FNG&qid=1650649326&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=tb6612fng%2Caps%2C71&sr=8-2) - $17

Sub-Total: $171.00 CAD

Option 2 - If building another Space Rover Build 1 (In addition to the above materials):
- [x] - 3D Print of Space Rover - ~$150
- [x] - [4 x Wheels](https://www.canadarobotix.com/products/1874) - $8
- [x] - [Arduino Uno/Mega](https://www.canadarobotix.com/products/60) - $28
- [x] - [NodeMCU](https://www.amazon.ca/KeeYees-Internet-Development-Wireless-Compatible/dp/B07HF44GBT/ref=sr_1_9?crid=2J7L7NRQHVZB8&keywords=nodeMCU&qid=1650651769&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=nodemcu%2Caps%2C108&sr=8-9) - $23
- [x] - [6x RGB LEDs](https://www.creatroninc.com/product/5mm-super-bright-led-rgb-cc/) - $11
- [ ] - [Headlights/Taillights](https://www.amazon.ca/Headlight-Taillight-Remote-Control-Accessory/dp/B07N842NYV/ref=sr_1_7?keywords=rc+headlight+kit&qid=1650652010&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=RC+headlight%2Caps%2C91&sr=8-7) - $10
- [ ] - [Red LEDs](https://www.creatroninc.com/product/5mm-led-red-10-pack/) - $1

Total: $231.00 CAD

**Good to Have - Common components between Build 1 and Build 2 :**
- [ ] - [MiniPC](https://www.amazon.ca/Beelink-Celeron-Processor-Business-Computer/dp/B09J2P5B89/ref=sr_1_23_sspa?crid=16C01SMYKK2LN&keywords=mini%2BPC&qid=1650652126&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=mini%2Bpc%2Caps%2C110&sr=8-23-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyVEdYVFZEQ0tES1VPJmVuY3J5cHRlZElkPUEwNTUyODcxMjhXQ0xEUVhDR1cwTCZlbmNyeXB0ZWRBZElkPUEwMjM2NjYzMkFSWUNYODVTV1A1UCZ3aWRnZXROYW1lPXNwX210ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1) - $288
- [ ] - [Logitech Keyboard/mouse](https://www.amazon.ca/Logitech-Wireless-Touch-Keyboard-920-007119/dp/B014EUQOGK/ref=sr_1_8?crid=28QX16ZC62JCC&keywords=logitech+keyboard+mouse+pad+mini&qid=1650652260&refinements=p_85%3A5690392011&rnid=5690384011&rps=1&sprefix=logitech+keyboard+mouse+pad+mini%2Caps%2C97&sr=8-8) - $40
- [x] - [Wifi Router](https://www.amazon.ca/TP-Link-TL-WR802N-Wireless-Repeater-300Mbps/dp/B00TQEX8BO/ref=sr_1_6?crid=WG4FX2HCFHNM&keywords=tp+link+nano+router+travel&qid=1650652206&sprefix=tp+link+nano+router+travel%2Caps%2C81&sr=8-6) - $35
- [ ] - Webcam/Macbook for the hand gesture system

**Comment by ellen-lau** [comment]
**Game Board List**
Option 1 - If re-purposing existing Game Board Build 1:
| ✓ | Item | Link | Price |
| :--: | ------------- | ------------- | ----- |
|<ul><li>[ ] </li></ul>| Wood |  |  |
|<ul><li>[ ] </li></ul>| Power Switch |  |  |

Sub-Total: 

Option 2 - If building another Game Board Build (In addition to the above materials):

| ✓ | Item | Link | Price |
| :--: | ------------- | :------------- | :----- |
|<ul><li>[ ] </li></ul>| Plexiglass |  |  |
|<ul><li>[ ] </li></ul>| Addressable LEDs in Grid Formation |  |  |
|<ul><li>[ ] </li></ul>| NodeMCU |  |  |
|<ul><li>[ ] </li></ul>| 3-Pin Wire Connectors |  |  |
|<ul><li>[ ] </li></ul>| Wires |  |  |
|<ul><li>[ ] </li></ul>| HCT125 Logic Level Shifter | https://elmwoodelectronics.ca/products/74ahct125-quad-level-shifter-3v-to-5v  | $2.99 |
|<ul><li>[ ] </li></ul>| Map Print | N/A | ~$40 |
|<ul><li>[ ] </li></ul>| Power Block (5V, ?A)  |  |  |

Total:

The same amount of person/weeks will be needed for each Option. Option 2 might require additional wait time to obtain the parts from due to shipping delays.
