### ISSUE TITLE
Add additional MicroProfile Features

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/space-rover-mission#67]
- Must add MP Fault Tolerance for the services (https://openliberty.io/guides/#fault_tolerance)
If time permits:
- MP JWT (Secure the Leaderboard service endpoint, need a certain role to update the leaderboard, Rover/GameBoard connection) (https://openliberty.io/guides/microprofile-jwt.html)
- MP OpenAPI (Leaderboard service already contains the annotations) (https://openliberty.io/guides/microprofile-openapi.html)

**Comment by jacobwdv** [comment]
open api complete with leaderboard work in #69
