### ISSUE TITLE
Add more game play metrics, with corresponding Grafana dashboard updates

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/space-rover-mission#68]
Currently, the Grafana dashboard just shows server stats and not specific game stats.  Add some good metrics that tell more about the details of game play.
Ideas:
- Get statistics on how many people played on a given day. 
- Avg. Rover Damage per day
- Aggregate data
- How many times blue planet got hit, --how many ppl crashed before completion...

**Comment by jacobwdv** [comment]
![image](https://user-images.githubusercontent.com/26169178/169141970-af34548c-1c89-404f-88ba-bc29592580c0.png)
added a new dashboard with some stats. The stats are fairly easy to add going forward. We can add / remove as we feel fit.
