### ISSUE TITLE
Add UI / REST API to interact  the leaderboard

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/space-rover-mission#69]
The below ideas, can be incorporated in the Settings page or in the leaderboard page.
- Delete a single user from the leaderboard.  
- Get statistics on how many people played on a given day.  (mpMetrics) 
- Ability to show the entire leaderboard.

**Comment by jacobwdv** [comment]
I also enabled open api to the leaderboard to generate the documentation to use our endpoints.
